# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mRlAYozqEZyRkMHZA33YJAIoUNH6G3-

# PROFESSIONAL DATA CLEANING UTILITY
##   Dataset : messy_ecommerce_sales_data.csv
#   Author  : Data Science Project
"""

import pandas as pd
import numpy as np
import os
from datetime import datetime

# ── CONFIG ───────────────────────────────────────────────────
INPUT_PATH  = "data/raw/messy_ecommerce_sales_data.csv"
OUTPUT_PATH = "data/cleaned/cleaned_ecommerce.csv"
LOG_PATH    = "logs/cleaning_log.txt"

CRITICAL_COLS   = ["order_id", "order_date"]   # rows missing these are dropped
OUTLIER_STD_DEV = 3                             # price outlier threshold

# ── LOGGER ───────────────────────────────────────────────────
log_entries = []

def record(msg):
    entry = f"[{datetime.now().strftime('%H:%M:%S')}] {msg}"
    log_entries.append(entry)
    print(entry)

# ── STEP 0 : LOAD ────────────────────────────────────────────
def load_data(path):
    df = pd.read_csv(path, skipinitialspace=True)
    record(f"Loaded: {df.shape[0]} rows × {df.shape[1]} columns from '{path}'")
    record(f"Columns: {list(df.columns)}")
    return df

# ── STEP 1 : COLUMN NAMES ────────────────────────────────────
def clean_column_names(df):
    df.columns = (
        df.columns
          .str.strip()
          .str.lower()
          .str.replace(" ", "_")
          .str.replace(r"[^a-z0-9_]", "", regex=True)
    )
    record(f"Standardized column names: {list(df.columns)}")
    return df

# ── STEP 2 : CATEGORY ────────────────────────────────────────
def clean_category(df):
    before = df["category"].unique()
    df["category"] = df["category"].str.strip().str.title()

    # Fix partial spellings
    df["category"] = df["category"].replace({
        "Electronic":  "Electronics",
        "Nan":          np.nan,
    })
    df["category"].fillna("Unknown", inplace=True)
    after = sorted(df["category"].unique())
    record(f"Category: {len(before)} variants → {len(after)} clean values: {after}")
    return df

# ── STEP 3 : PRODUCT NAMES ───────────────────────────────────
def clean_product(df):
    df["product"] = df["product"].str.strip().str.title()
    record("Standardized product names to title case")
    return df

# ── STEP 4 : PRICE ───────────────────────────────────────────
def clean_price(df):
    record("─── Price cleaning ───")

    # Strip non-numeric characters (e.g. '$', letters)
    df["price"] = df["price"].astype(str).str.replace(r"[^\d.\-]", "", regex=True)
    df["price"] = pd.to_numeric(df["price"], errors="coerce")

    # Remove negative prices
    neg = df[df["price"] < 0]
    if len(neg):
        record(f"  Negative prices ({len(neg)} rows) → set to NaN: "
               f"{neg[['id','product','price']].values.tolist()}")
        df.loc[df["price"] < 0, "price"] = np.nan

    # Remove statistical outliers (> mean + N*std)
    μ, σ = df["price"].mean(), df["price"].std()
    thresh = μ + OUTLIER_STD_DEV * σ
    outliers = df[df["price"] > thresh]
    if len(outliers):
        record(f"  Price outliers > {thresh:.0f} ({len(outliers)} rows) → set to NaN: "
               f"{outliers[['id','product','price']].values.tolist()}")
        df.loc[df["price"] > thresh, "price"] = np.nan

    # Fill missing prices with category-level median, then global median
    before_null = df["price"].isnull().sum()
    df["price"] = df.groupby("category")["price"].transform(
        lambda x: x.fillna(x.median())
    )
    df["price"].fillna(df["price"].median(), inplace=True)
    record(f"  Filled {before_null} missing prices (category median → global median)")
    record(f"  Price nulls remaining: {df['price'].isnull().sum()}")
    return df

# ── STEP 5 : QUANTITY ────────────────────────────────────────
def clean_quantity(df):
    record("─── Quantity cleaning ───")

    # Extract leading digits (handles '4a' → 4)
    df["quantity"] = df["quantity"].astype(str).str.extract(r"(-?\d+)", expand=False)
    df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")

    # Remove negative quantities (returns/errors — can't have negative stock)
    neg = df[df["quantity"] < 0]
    if len(neg):
        record(f"  Negative quantities ({len(neg)} rows) → set to NaN")
        df.loc[df["quantity"] < 0, "quantity"] = np.nan

    # Fill with median
    before_null = df["quantity"].isnull().sum()
    df["quantity"].fillna(df["quantity"].median(), inplace=True)
    df["quantity"] = df["quantity"].astype(int)
    record(f"  Filled {before_null} missing quantities with median = {int(df['quantity'].median())}")
    return df

# ── STEP 6 : DATES ───────────────────────────────────────────
def clean_dates(df):
    record("─── Date cleaning ───")

    df["order_date"] = pd.to_datetime(df["order_date"], format="mixed", errors="coerce")

    # Drop rows where date is completely unparseable
    bad = df["order_date"].isnull().sum()
    if bad:
        record(f"  Dropping {bad} rows with unparseable dates")
        df.dropna(subset=["order_date"], inplace=True)

    # Flag suspicious historical dates
    old = df[df["order_date"].dt.year < 2024]
    if len(old):
        record(f"  WARNING: {len(old)} orders dated before 2024 — keeping but flagging")
        df["date_flag"] = np.where(df["order_date"].dt.year < 2024, "SUSPICIOUS_DATE", "")

    # Feature engineering
    df["order_year"]       = df["order_date"].dt.year
    df["order_month"]      = df["order_date"].dt.month
    df["order_month_name"] = df["order_date"].dt.strftime("%B")
    record("  Extracted: order_year, order_month, order_month_name")
    return df

# ── STEP 7 : TOTAL ───────────────────────────────────────────
def clean_total(df):
    original_total = pd.to_numeric(df["total"], errors="coerce")
    df["total"]    = (df["price"] * df["quantity"]).round(2)
    mismatch       = (abs(original_total - df["total"]) > 0.5).sum()
    record(f"Recalculated all totals (Price × Qty). Fixed {mismatch} mismatches.")
    return df

# ── STEP 8 : DUPLICATES ──────────────────────────────────────
def remove_duplicates(df):
    before = len(df)
    df.drop_duplicates(inplace=True)
    removed_exact = before - len(df)

    before = len(df)
    df.sort_values("total", ascending=False, inplace=True)
    df.drop_duplicates(subset=["order_id"], keep="first", inplace=True)
    df.sort_values("id", inplace=True)
    removed_orderid = before - len(df)

    record(f"Duplicates removed: {removed_exact} exact + {removed_orderid} duplicate Order_IDs")
    return df

# ── STEP 9 : FINAL VALIDATION ────────────────────────────────
def validate(df):
    record("─── Final validation ───")
    assert df["price"].isnull().sum() == 0,    "Price has nulls!"
    assert df["quantity"].isnull().sum() == 0, "Quantity has nulls!"
    assert df["category"].isnull().sum() == 0, "Category has nulls!"
    assert (df["price"] >= 0).all(),           "Negative prices found!"
    assert (df["quantity"] >= 0).all(),        "Negative quantities found!"
    record("  All validation checks passed ✓")
    record(f"  Final shape: {df.shape[0]} rows × {df.shape[1]} columns")
    record(f"  Total nulls remaining: {df.isnull().sum().sum()}")

# ── SAVE ─────────────────────────────────────────────────────
def save_outputs(df):
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    df.to_csv(OUTPUT_PATH, index=False)
    record(f"Saved cleaned data → {OUTPUT_PATH}")

    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "w") as f:
        f.write("\n".join(log_entries))
    record(f"Saved cleaning log → {LOG_PATH}")

# ── MAIN PIPELINE ─────────────────────────────────────────────
def run_pipeline(input_path=INPUT_PATH):
    record("=" * 60)
    record("ECOMMERCE DATA CLEANING PIPELINE — START")
    record("=" * 60)

    df = load_data(input_path)
    original_shape = df.shape

    df = clean_column_names(df)
    df = clean_category(df)
    df = clean_product(df)
    df = clean_price(df)
    df = clean_quantity(df)
    df = clean_dates(df)
    df = clean_total(df)
    df = remove_duplicates(df)

    record("=" * 60)
    record("CLEANING SUMMARY")
    record(f"  Input  : {original_shape[0]} rows × {original_shape[1]} columns")
    record(f"  Output : {df.shape[0]} rows × {df.shape[1]} columns")
    record(f"  Dropped: {original_shape[0] - df.shape[0]} rows")
    record("=" * 60)

    validate(df)
    save_outputs(df)
    return df


if __name__ == "__main__":
    cleaned_df = run_pipeline(
        input_path="/content/messy_ecommerce_sales_data.csv"
    )
    print("\nSample output:")
    print(cleaned_df[["id","product","category","order_date",
                       "quantity","price","total","status"]].head(10))